{
 "title": "main db for LAB2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Top categories",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    category_id,\r\n    offers_cnt\r\nFROM ecom.catalog_by_category_mv\r\nORDER BY offers_cnt DESC\r\nLIMIT 20;\r\n"
    }
   ]
  },
  {
   "title": "Top-30 brands by number of offers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    vendor,\r\n    sum(offers_cnt) AS offers_cnt\r\nFROM ecom.catalog_by_brand_mv\r\nGROUP BY vendor\r\nORDER BY offers_cnt DESC\r\nLIMIT 30;\r\n"
    }
   ]
  },
  {
   "title": "Offers without events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    countIf(ev.offer_id IS NULL) AS offers_without_events\r\nFROM ecom.ecom_offers AS o\r\nLEFT JOIN ecom.offer_events_mv AS ev\r\n    ON o.offer_id = ev.offer_id;\r\n"
    }
   ]
  },
  {
   "title": "Catalogue coverage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    countIf(ev.offer_id IS NOT NULL) AS offers_with_events,\r\n    count()                          AS total_offers,\r\n    offers_with_events / total_offers AS coverage_ratio\r\nFROM ecom.ecom_offers AS o\r\nLEFT JOIN ecom.offer_events_mv AS ev\r\n    ON o.offer_id = ev.offer_id;\r\n"
    }
   ]
  },
  {
   "title": "Average query latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_QueryTimeMicroseconds[1m])\r\n/\r\nrate(ClickHouseProfileEvents_Query[1m])\r\n/ 1e6\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Query[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking\r\n/ 1e9",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}